mayadata-io/d-operators

- Makefile
- common/unstruct/list.go
- common/unstruct/list_test.go
- controller/run/assert.go
- controller/run/assert_test.go
- controller/run/createordelete_test.go
- controller/run/task.go
- controller/run/update.go
- controller/run/update_test.go
- types/run/types.go
This commit is a continuation to implement Run controller.
It includes implementation of following:
- update logic,
- additional unit tests,
- renaming variables
> feat(run): add update logic to run controller

- controller/run/createordelete.go
- controller/run/createordelete_test.go
- controller/run/task.go
- controller/run/task_test.go
- controller/run/update.go
- controller/run/update_test.go
- go.sum
- types/run/types.go
> feat(run): add unit tests to various run actions

- controller/run/assert.go
- controller/run/assert_test.go
- controller/run/create.go
- controller/run/create_test.go
- controller/run/createordelete.go
- controller/run/delete.go
- controller/run/delete_test.go
- controller/run/run.go
- controller/run/run_test.go
- controller/run/task.go
- controller/run/task_test.go
- controller/run/update.go
- controller/run/update_test.go
- types/run/types.go
This commit also includes changes to Run schema.
> feat(run): add logic to execute all tasks

- controller/run/assert.go
- controller/run/create.go
- controller/run/create_test.go
- controller/run/delete.go
- controller/run/delete_test.go
- controller/run/run.go
- controller/run/run_test.go
- controller/run/task.go
- controller/run/task_test.go
- controller/run/update.go
- controller/run/update_test.go
- types/run/types.go
> feat(run): add unit tests & code fixes w.r.t run logic

- README.md
> chore(readme): update readme on declarative pattern

- README.md
- controller/run/assert.go
- controller/run/assert_test.go
- controller/run/run.go
- controller/run/run_test.go
- controller/run/task.go
- types/run/types.go
> chore(unittest): add various unit tests for Run resource

- README.md
- cmd/main.go
- common/controller/reconciler.go
- controller/run/assert.go
- controller/run/assert_test.go
- controller/run/reconciler.go
- controller/run/run_test.go
- types/run/types.go
> chore(unit-test): add tests to validate the Run logic

- README.md
- types/cronresource/types.go
This commit makes a few changes to README as well.
> feat(cron): add cron resource schema

- controller/run/assert.go
- controller/run/assert_test.go
- controller/run/run.go
- controller/run/run_test.go
- controller/run/task.go
- controller/run/task_test.go
- types/run/types.go
closes https://github.com/mayadata-io/d-operators/issues/52
> chore(run): refactor run schema to make it more readable

- .github/PULL_REQUEST_TEMPLATE.md
- .github/semantic.yml
- .github/workflows/release-docker.yaml
- .github/workflows/test-release.yaml
- CONTRIBUTING.md
- release.config.js
> feat(gh-actions): add workflows & semantic release conventions

- Dockerfile
> fix(build): add pkg package to Dockerfile

- .github/workflows/release-docker.yaml
> fix(build): update docker user & pw to gh actions release image

- cmd/main.go
- controller/job/reconciler.go
- go.mod
- go.sum
- pkg/job/apply.go
- pkg/job/assert.go
- pkg/job/base.go
- pkg/job/common.go
- pkg/job/create.go
- pkg/job/eligible.go
- pkg/job/errors.go
- pkg/job/fixture.go
- pkg/job/job.go
- pkg/job/lock.go
- pkg/job/path_check.go
- pkg/job/retry.go
- pkg/job/state_check.go
- pkg/job/task.go
- test/experiments/assert-deprecated-daemonset.yaml
- test/experiments/assert-job-teardown.yaml
- test/experiments/assert-lock-persists-for-job-that-runs-once.yaml
- test/experiments/create-assert-fifty-configmaps-elapsedtime.yaml
- test/experiments/inference.yaml
- test/pkg/setup/controlplane/runner.go
- test/setup/controlplane/setup.yaml
- test/suite.go
- types/gvk/gvk.go
- types/job/job.go
- types/job/task.go
This commit has following features:
- eligible check to enable or disable a job
- thinkTimeInSeconds to delay start of a Job
- failFast to stop retrying in case of specific errors
- ignoreError to mark a task as warning & job to completed
> feat(job): add eligible tunable

- Makefile
- pkg/job/eligible_test.go
- pkg/job/fixture.go
- types/job/job.go
> chore(unittests): add tests for eligibility logic

- Makefile
- pkg/job/fixture.go
- pkg/job/fixture_test.go
- pkg/job/job.go
- pkg/job/job_test.go
- pkg/job/noop.go
- test/experiments/assert-deprecated-daemonset.yaml
- types/job/task.go
In addition, this commit adds few unit test cases
> feat(job): update failfast schema

- deploy/operator.yaml
Signed-off-by: Amit Bhatt <amitbhatt818@gmail.com>
- This PR adds statefulset yml which will help in deploying dope.
> [fix]:Added statefulset yaml to deploy dope

- config/metac.yaml
- controller/recipe/reconciler.go
- manifests/crd.yaml
- test/e2e/ci.yaml
- test/e2e/inference.yaml
- test/e2e/suite.sh
- test/experiments/assert-deprecated-daemonset.yaml
- test/experiments/assert-github-search-invalid-method-negative.yaml
- test/experiments/assert-github-search-invalid-method.yaml
- test/experiments/assert-github-search-neg.yaml
- test/experiments/assert-github-search.yaml
- test/experiments/assert-job-teardown.yaml
- test/experiments/assert-lock-persists-for-job-that-runs-once.yaml
- test/experiments/create-assert-fifty-configmaps-elapsedtime.yaml
- test/experiments/create-assert-fifty-configmaps.yaml
- test/experiments/crud-ops-on-pod.yaml
- types/gvk/gvk.go
> fix(gvk): update group from metacontroller.io to mayadata.io

- README.md
> chore(readme): fix indentation

- cmd/commander/Makefile
- cmd/commander/pkg/run_command.go
- cmd/commander/pkg/shell_command.go
- test/e2e/inference.yaml
- test/experiments/assert-recipe-lock-is-garbage-collected.yaml
> fix(e2e): remove flaky garbage check from e2e

- Dockerfile
- cmd/commander/main.go
- cmd/commander/pkg/run_command.go
- cmd/commander/pkg/shell_command.go
> fix(commander): fix int64 to float64 conversion error

- cmd/commander/Dockerfile
> fix(commander): update dcmd to use Alpine base image

- pkg/recipe/recipe.go
> fix(recipe): fix code to execute recipe via function calls

- .github/workflows/release-docker.yaml
Signed-off-by: Amit Bhatt <amit.bhatt@mayadata.io>
> feat(build): push docker image to hub for d-action

- .github/workflows/release-docker.yaml
Signed-off-by: Amit Bhatt <amit.bhatt@mayadata.io>
> feat(build): change repo name for dockerhub

- pkg/recipe/recipe.go
> feat(recipe): include fixture as part of recipe initialization

- types/recipe/recipe.go
> feat(recipe): add pretty print to recipe structure

- types/recipe/schema.go
> fix(recipe): add spec.enabled.when as a supported recipe schema

- .github/workflows/release-docker.yaml
- Makefile
- tools/d-action/Makefile
> fix(build): add latest tag during docker push

- .github/workflows/test-release.yaml
- Makefile
- tools/d-action/Makefile
Signed-off-by: Amit Bhatt <amit.bhatt@mayadata.io>
> fix(build): push latest image of d-action and dope

- .github/workflows/latest-image-push.yaml
- .github/workflows/test-release.yaml
Signed-off-by: Amit Bhatt <amitbhatt818@gmail.com>
> fix(build): add latest image push yaml

- .github/workflows/latest-image-push.yaml
Signed-off-by: Amit Bhatt <amitbhatt818@gmail.com>
> fix(build): change variabl name for docker credentials

- pkg/kubernetes/retry.go
- pkg/kubernetes/utility.go
- pkg/recipe/base.go
- pkg/recipe/eligible.go
- pkg/recipe/recipe.go
- pkg/recipe/recipe_test.go
- test/e2e/inference.yaml
- test/experiments/assert-github-search-invalid-method-neg.yaml
- test/experiments/assert-github-search-invalid-method.yaml
> feat(client): add resuable kubernetes client package

- pkg/kubernetes/utility.go
- pkg/recipe/list.go
> fix(discovery): add retries to discover kubernetes api

- pkg/recipe/get.go
- types/recipe/get.go
Signed-off-by: Amit Bhatt <amit.bhatt@mayadata.io>
> feat(get): add code to get resource

- pkg/recipe/list.go
Signed-off-by: Rohan Kumar <rohan.kumar@mayadata.io>
> feat(recipe): add label selector to list resources

- pkg/recipe/apply.go
- pkg/recipe/create.go
- pkg/recipe/fixture.go
> feat(crd): add v1 apis to apply CRDs

- pkg/recipe/recipe.go
> fix(recipe): fix recipe constructor to use config field

- go.mod
- go.sum
- pkg/recipe/fixture.go
This PR adds the method to discover list of resources based
provided kind. This functionality will help consumers to get
resource details based on Kind.
**:memo: To Reviewers**:
- This PR is dependent on [PR](https://github.com/AmitKumarDas/metac/pull/151).
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
> feat(discovery): add method to list resources based on kind 
